### ISSUE TITLE
2.4.0 breaks usage within vue (exports corrupt)

### ISSUE THREAD

**Issue by Morl99** [awslabs/amazon-quicksight-embedding-sdk#171]
Hello @jonathanRinciari,

we are using this sdk within our application and are trying to update it to 2.4.0. Unfortunately, this does not seem to work. We tried to incorporate all changes in the typings that you made and the typescript compiler is now happy again. When we build the app with vite (the build-tool that comes with vue 3), it breaks with the following exception:

```
[vite:vue] Export 'createEmbeddingContext' is not defined.
```

Digging around in the typings that version 2.4.0 includes, at least one issue becomes clear: The `createEmbeddingContext` is declared/exported twice. Once in line 868 and once in line 1009. We think, that babel (that is used within vite) cannot cope with that illegal declaration and thus prints the above error message. 

I hope this helps in fixing the issue. Let us know, if you need additional details.

For some more context, here is our code snippet:

```TypeScript
import QS from "amazon-quicksight-embedding-sdk"
const embeddingContext = ref<EmbeddingContext>()
embeddingContext.value = await QS.createEmbeddingContext({
    onChange: (changeEvent, metadata) => {
      emit("change", { changeEvent, metadata })
    },
  })
```

**Comment by jonathanRinciari** [comment]
Hey @Morl99,

Thank you for taking the time to report the issue that you are having. I did some digging and it looks like the error is coming from [babel-parser](https://github.com/babel/babel/blob/888903e87c8f458a0d548f8addbe3aa12fef9196/packages/babel-parser/src/parse-error/standard-errors.ts#L209). 

In the code sample that was provided a default import is assigned to `QS` and the `createEmbeddingContext` method is called. However, we do not expose a default export so the value of `QS` is undefined hence the babel-parser error. 

It is likely that your tsconfig has `allowSyntheticDefaultImports` enabled which allows the default import syntax when the module doesn’t have a default export. You can test this by setting the value to false in your config.

Try updating your import to one of the following options. 

1. `import * as QS from ‘amazon-quicksight-embedding-sdk’`
2. `import { createEmbeddingContext } from ‘amazon-quicksight-embedding-sdk’`

If you are still having issues let me know and I can try to assist further.

Thanks,
Jon 


- https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports

**Comment by d-koppenhagen** [comment]
@jonathanRinciari I got the same error once I try to update the dependency from version 2.3.1 to 2.4.0 in my Vue wrapper library for this lib: https://github.com/dbsystel/v-quicksight

I got the following error message after the update:

```
[@vue/compiler-sfc] Failed to resolve import source "amazon-quicksight-embedding-sdk/dist/types".

/Users/dannykoppenhagen/dev/v-quicksight/src/types.ts
5  |  } from "amazon-quicksight-embedding-sdk/dist/types"
6  |  
7  |  export type VQuicksightFrameOptions = Omit<FrameOptions, "onChange" | "container">
   |                                             ^^^^^^^^^^^^
8  |  export type VQuicksightDashboardContentOptions = Omit<DashboardContentOptions, "onMessage">
9  |  export type VQuicksightVisualContentOptions = Omit<VisualContentOptions, "onMessage">
09:26:38 [vitepress] Internal server error: [@vue/compiler-sfc] Failed to resolve import source "amazon-quicksight-embedding-sdk/dist/types".

/Users/dannykoppenhagen/dev/v-quicksight/src/types.ts
5  |  } from "amazon-quicksight-embedding-sdk/dist/types"
6  |  
7  |  export type VQuicksightFrameOptions = Omit<FrameOptions, "onChange" | "container">
   |                                             ^^^^^^^^^^^^
8  |  export type VQuicksightDashboardContentOptions = Omit<DashboardContentOptions, "onMessage">
9  |  export type VQuicksightVisualContentOptions = Omit<VisualContentOptions, "onMessage">
  Plugin: vite:vue
  File: /Users/dannykoppenhagen/dev/v-quicksight/src/components/VQuicksightVisual.vue
      at ScriptCompileContext.error (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:15656:11)
      at importSourceToScope (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18273:16)
      at resolveTypeFromImport (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18234:23)
      at innerResolveTypeReference (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18136:14)
      at resolveTypeReference (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18125:36)
      at innerResolveTypeElements (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:17779:24)
      at resolveTypeElements (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:17736:35)
      at resolveBuiltin (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18076:13)
      at innerResolveTypeElements (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:17788:20)
      at resolveTypeElements (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:17736:35)
[@vue/compiler-sfc] Failed to resolve import source "amazon-quicksight-embedding-sdk/dist/types".

/Users/dannykoppenhagen/dev/v-quicksight/src/types.ts
5  |  } from "amazon-quicksight-embedding-sdk/dist/types"
6  |  
7  |  export type VQuicksightFrameOptions = Omit<FrameOptions, "onChange" | "container">
   |                                             ^^^^^^^^^^^^
8  |  export type VQuicksightDashboardContentOptions = Omit<DashboardContentOptions, "onMessage">
9  |  export type VQuicksightVisualContentOptions = Omit<VisualContentOptions, "onMessage">
```

My IDE also shows me, that the type declarations couldn't be found:

![Bildschirmfoto 2023-11-01 um 09 43 08](https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/4279702/d624d09c-a6ba-48be-a983-b15bf5f7316c)

A bit strange is, that revealing the `node_modules` shows three level of dist dirs with `index.d.ts` files:

![Bildschirmfoto 2023-11-01 um 09 44 49](https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/4279702/ddb58ccb-1ada-4156-a4f9-f28adfc232e6)

**Comment by d-koppenhagen** [comment]
Okay, just digged a bit deeper into it. 

I think here are two issues:

### Changes types / imports

there were breaking changes introduced, which confused me. The following are the ones I identified. can you may add them to the CHANGELOG.md?

- type importes changed from `amazon-quicksight-embedding-sdk/dist/types` to `amazon-quicksight-embedding-sdk`.
- Some type names have been changed (probably more?):
```diff
import type {
-  DashboardFrame,
+  DashboardExperience
-  VisualFrame
+  VisualExperience
-  SimpleChangeEvent,  SimpleMessageEvent
+  EmbeddingEvents
-} from 'amazon-quicksight-embedding-sdk/dist/types'
+} from 'amazon-quicksight-embedding-sdk'
```

### `createEmbeddingContext` could not be found

The initial reported error does still occur. Starting my project with vitepress reveals a bit more details though:

```
Error in error handler:
Error: offset is longer than source length! offset 50442 > length 2989
    at numberToPos (file:///Users/dannykoppenhagen/dev/v-quicksight/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:12117:15)
    at formatError (file:///Users/dannykoppenhagen/dev/v-quicksight/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44080:35)
    at TransformContext.error (file:///Users/dannykoppenhagen/dev/v-quicksight/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44058:19)
    at Object.transform (file:///Users/dannykoppenhagen/dev/v-quicksight/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44355:25)
    at async loadAndTransform (file:///Users/dannykoppenhagen/dev/v-quicksight/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55026:29)
    at async viteTransformMiddleware (file:///Users/dannykoppenhagen/dev/v-quicksight/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:64430:32)

10:04:53 [vitepress] Internal server error: Export 'createEmbeddingContext' is not defined. (1009:13)
  Plugin: vite:vue
  File: /Users/dannykoppenhagen/dev/v-quicksight/src/components/VQuicksightVisual.vue:1009:13
      at constructor (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@babel/parser/lib/index.js:356:19)
      at TypeScriptParserMixin.raise (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@babel/parser/lib/index.js:3223:19)
      at TypeScriptParserMixin.parseProgram (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@babel/parser/lib/index.js:12472:14)
      at TypeScriptParserMixin.parseTopLevel (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@babel/parser/lib/index.js:12459:25)
      at TypeScriptParserMixin.parse (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@babel/parser/lib/index.js:14381:10)
      at TypeScriptParserMixin.parse (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@babel/parser/lib/index.js:9987:18)
      at Object.parse (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@babel/parser/lib/index.js:14422:38)
      at parseFile (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18394:21)
      at fileToScope (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18385:16)
      at importSourceToScope (/Users/dannykoppenhagen/dev/v-quicksight/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:18271:12)
```

I think the problematic part is this one: `Error: offset is longer than source length! offset 50442 > length 2989`.

I think there is some error in the created `types.ts` file which causes this problem.

**Comment by jonathanRinciari** [comment]
@d-koppenhagen I was able to reproduce the issue by pulling down your package and updating to 2.4.0. It looks like the problem is with `declare module` found inside of the index.d.ts. This file is a dts rollup that is auto-generated during the build to avoid having to import types from a subpath. A fix will be included in the next release. Thanks for bringing this issue to our attention.

**Comment by d-koppenhagen** [comment]
Great, that you were able to reproduce it. Looking forward for the next release! Thank you!

**Comment by d-koppenhagen** [comment]
Is there anything I can do to get the fix/next release flying?

**Comment by d-koppenhagen** [comment]
Awesome, with version 2.5.0 it's fixed now. Thanks!

**Comment by Morl99** [comment]
Great!
