### ISSUE TITLE
DashboardExperience.getFilterGroupsForSheet(sheetId) Error

### ISSUE THREAD

**Issue by brianwyka** [awslabs/amazon-quicksight-embedding-sdk#201]
An error occurs the first time the `DashboardExperience.getFilterGroupsForSheet(sheetId)` function is called.
On subsequent calls, the error does not occur.  I noticed that the `l` variable in the code image below has a state of `loading` which is probably the issue...

**Error:**
```
embedding-bootstrap.…f7e16344acf.44.js:2 Uncaught (in promise) TypeError: l.map is not a function
    at embedding-bootstrap.…44acf.44.js:2:21465
    at Generator.next (<anonymous>)
    at dt (embedding-bootstrap.…44acf.44.js:2:14553)
    at s (embedding-bootstrap.…44acf.44.js:2:14757)
```

**See offending code below:**
<img width="985" alt="image" src="https://github.com/awslabs/amazon-quicksight-embedding-sdk/assets/46069296/7be9f72f-d6b0-4cff-9669-86363a438a3f">

**Version**
`2.6.0`

**Comment by brianwyka** [comment]
Unfortunately the source map fails to load - #143 , so debugging is not too easy.

**Comment by brianwyka** [comment]
@kuehnmic, yes.
