### ISSUE TITLE
Create share view

### ISSUE THREAD

**Issue by derf-github** [awslabs/amazon-quicksight-embedding-sdk#222]
Hello,

I'm working on the embedding of dashboards and their sharing using the newly added [createSharedView](https://github.com/awslabs/amazon-quicksight-embedding-sdk?tab=readme-ov-file#-createsharedview---promiseresponsemessage) function.

I've followed the different steps described in the [AWS documentation](https://docs.aws.amazon.com/quicksight/latest/user/embedded-view-sharing.html). I'm able to generate a shareable link from the application displaying the embedded dashboard BUT once the shareable link has been used, I cannot generate any new shareable link from my application and I get the following error : 

```
Uncaught (in promise) Error: Failed to read custom view with id CUSTOM_VIEW_ID for user: arn:aws:quicksight::**************:user-internal/idc/ID/IDENTITY_STORE_ID/GENERATED_UUID
    at embedding.5db521eadc97c379.49.js:2:144854
    at Generator.next (<anonymous>)
    at L (embedding.5db521eadc97c379.49.js:2:144036)
    at a (embedding.5db521eadc97c379.49.js:2:144239)
    ...
Uncaught (in promise) {errorCode: 'CUSTOM_VIEW_DOES_NOT_EXIST', message: 'Failed to read custom view with id CUSTOM_VIEW_ID…ITY_STORE_ID/GENERATED_UUID', httpStatus: 404, responseObject: {…}}
    o @ embedding.5db521eadc97c379.49.js:2
    l @ embedding.5db521eadc97c379.49.js:2
    Promise.then (async)
    o @ embedding.5db521eadc97c379.49.js:2
    s @ embedding.5db521eadc97c379.49.js:2
    ...
Uncaught (in promise) Error: Failed to read custom view with id CUSTOM_VIEW_ID for user: arn:aws:quicksight::**************:user-internal/idc/ID/IDENTITY_STORE_ID/GENERATED_UUID
    at embedding.5db521eadc97c379.49.js:2:144854
    at Generator.next (<anonymous>)
    at L (embedding.5db521eadc97c379.49.js:2:144036)
    at a (embedding.5db521eadc97c379.49.js:2:144239)
    (anonymous) @ embedding.5db521eadc97c379.49.js:2
    L @ embedding.5db521eadc97c379.49.js:2
    ...
Uncaught (in promise) CREATE_SHARED_VIEW timed out
```

Here's the code used to embed the dashboard

```
const quicksightButton = document.getElementById("quicksightButton");
const dashboardExperience = await embedDashboard("MY_DASHBOARD_ID");

quicksightButton.addEventListener("click", async function() {
    var link = document.getElementById("quicksightLink");
    link.href="";
    link.innerText="";

    response = await dashboardExperience.createSharedView();
    sharedViewId = response.message.sharedViewId;

    response = await fetch('${api_gateway_url}/dashboard-self-service/embed-url/' + dashboardId);
    responseUrl = await response.json();
    embedUrl = responseUrl['EmbedUrl'];

    const formattedUrl = new URL(embedUrl);
    formattedUrl.pathname = formattedUrl.pathname.concat('/views/' + sharedViewId);

    link.href=formattedUrl.href;
    link.innerText="Link to dashboard " + dashboardId + " and view " + sharedViewId;
});


const embedDashboard = async (dashboardId) => {
    removeDashboard();
    const response = await fetch('${api_gateway_url}/dashboard-self-service/embed-url/' + dashboardId);
    const responseUrl = await response.json();

    embedUrl = responseUrl['EmbedUrl'];

    const {
        createEmbeddingContext,
    } = QuickSightEmbedding;

    const embeddingContext = await createEmbeddingContext();

    const frameOptions = {
        url: embedUrl,
        container: document.getElementById("embedding-container"),
        withIframePlaceholder: true,
        height: "AutoFit",
        loadingHeight: "700px"
    };

    const contentOptions = {
        onMessage: async (messageEvent, metadata) => {
            switch (messageEvent.eventName) {
                case 'CONTENT_LOADED': {
                    document.getElementById("quicksightButton").disabled=false;
                    document.getElementById("currentPageButton").disabled=false;
                    break;
                }
                case 'ERROR_OCCURRED': {
                    console.log("Do something when the embedded experience fails loading.");
                    break;
                }
                case 'PAGE_NAVIGATION': {
                    setPageType(messageEvent.message.pageType);
                    if (messageEvent.message.pageType === 'DASHBOARD') {
                        setShareEnabled(true);
                        } else {
                        setShareEnabled(false);
                    }
                    break;
                }
            }
        }
    };

    return embeddingContext.embedDashboard(frameOptions, contentOptions);
};
```

Am I missing something?

Thanks for you help.

**Comment by huaraymo** [comment]
Is this being done through registered or anonymous embedding?

**Comment by derf-github** [comment]
It is done through registered embedding.
